### ISSUE TITLE
pathoscope install 

### ISSUE THREAD

**Issue by ziyewang** [liuyu8721/CSMD#2]
Dear Liu,

Do I need to install pathoscope with the complete PathoDB and download the complete NT library with the taxonomy id to use CSMD?

Best,
Ziye

**Comment by liuyu8721** [comment]
Hi Ziye,

You only need to download pathoscope from https://sourceforge.net/projects/pathoscope/, then uncompress it and configure it in 'config.sh'.
And yes, you need to download nt database and taxonomy files, please see the CSMD installation in Section 4.3 and 4.4.

Best,
Yu

**Comment by ziyewang** [comment]
Thanks.
