### ISSUE TITLE
Can we adjust the maximum memory usage?

### ISSUE THREAD

**Issue by TAITAI-GAMESTUDIO** [liuyu8721/CSMD#3]
Dear Liu，

We want to try your pipeline, but currently the maximum memory of our lab server is only 128G. So is there any chance for us to adjust the maximum memory usage?

Best,
Tai

**Comment by liuyu8721** [comment]
Hi Tai,
 
The memory with 128G for CS step is OK but is not good for MD step. In MD step, the RefSeq microbial database is too big to be indexed using 128G memory.  
I don't know what is your study question? If it is a microbiome analysis for clinical samples, at least, CS step is necessary to reduce the false positive discovery (please refer to Supplementary Figure S2 in the paper). So, a compromise solution may be to use CS process then other profile tools.

Best,
Yu
